In [2]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
print(a, b, sep = '\n')


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
c = np.arange(10)
d = np.arange(10, 20)
print(c, d, sep = '\n')
e = np.concatenate((c, d))
print(e)
f = np.arange(10, 20, 2)
print(f)

print(c*d)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[  0  11  24  39  56  75  96 119 144 171]


In [13]:
print(np.linspace(0, 1, 10))
print(np.linspace(0, 1, 10, endpoint=False))
print(np.linspace(0, 9, 10, dtype=int, endpoint=False))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 0 1 2 3 4 5 6 7 8]


In [35]:
print(np.logspace(1, 10, 10, base=2))    
print(np.logspace(0, 5, 6))
print(np.logspace(2, 6, 5, base=3))

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
[  9.  27.  81. 243. 729.]


In [38]:
print(np.zeros(10))
print(np.ones((3,3), dtype=int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
