In [1]:
import numpy as np
numbers = np.random.randint(1, 100, 10)
evens = numbers[numbers % 2 == 0]
odds = numbers[numbers % 2 == 1]
print("Numbers: ", numbers)
print("Evens: ", evens)
print("Odds: ", odds)



Numbers:  [78  2 69 20 78 49  1 65 97 99]
Evens:  [78  2 20 78]
Odds:  [69 49  1 65 97 99]


In [3]:
# generate array of 10 names
names = np.array(['Alice', 'Bob', '', 'Dan', '', 'Frank', 'Gary', 'Helen', 'Irene', 'Jack'])
ages = np.random.randint(-200, 200, 10)

#change empty names to 'John Doe'
names[names == ''] = 'John Doe'

#change negative ages to 0 and ages over 150 to 150
ages[ages < 0] = 0
ages[ages > 150] = 150
print("Names: ", names)
print("Ages: ", ages)


Names:  ['Alice' 'Bob' 'John ' 'Dan' 'John ' 'Frank' 'Gary' 'Helen' 'Irene' 'Jack']
Ages:  [  0 150   0 139 150   0  18   0   0 150]


In [8]:
y = np.array([0.,1.3,5.,10.9,18.9,28.7,40.])
t = np.array([0.,0.49,1.,1.5,2.08,2.55,3.2])
v = np.zeros(len(y))
v[1:] = (y[1:] - y[:-1])/(t[1:] - t[:-1])
print("Velocity: ", v)

Velocity:  [ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [16]:
# 2d list
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
print("2d list: ", a)
print("2d array: ", b)
print(np.shape(b))
# 1d list
c = [1,2,3,4,5,6,7,8,9]
d = np.array(c)
print("1d list: ", c)
print("1d array: ", d)
d = d.reshape(3,3)
print("1d list: ", c)
print("2d array: ", d)

2d list:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1d list:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
1d array:  [1 2 3 4 5 6 7 8 9]
1d list:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(np.zeros((3,3)))
matrix = np.random.randint(1, 100, (4,3))
print(matrix)
print(matrix[:,:1])
print(matrix[1:-1,1:])


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[76 96 38]
 [63 10 26]
 [98 61 33]
 [42 88 19]]
[[76]
 [63]
 [98]
 [42]]
[[10 26]
 [61 33]]


In [2]:
import numpy as np
matrix1 = np.zeros((8,8), dtype=int)
matrix1[0:,0:1] = 1
matrix1[:1,0:] = 1
matrix1[0:,-1:] = 1
matrix1[-1:,0:] = 1
print(matrix1)

matrix2 = np.zeros((8,8), dtype=int)
matrix2[1::2,1::2] = 1
matrix2[0::2,0::2] = 1
print(matrix2)

a = np.array(([1,0] * 4 + [0,1] * 4)*4).reshape(8,8)
print(a)


[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


: 